plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "backend"
include(":application")
include(":commons")
include(":users")
include(":properties")
include("notification")
include("customers")
