server:
  port: 8080
  servlet:
    context-path: /application
  tomcat:
    accesslog:
      enabled: true
spring:
  liquibase:
    change-log: db/changelog/master.yaml

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        context: DEBUG

ofdata:
  key: MVZE7dtgCniGVwgV