/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:3.3.1")
    api("org.springframework.boot:spring-boot-starter-validation:3.3.1")
    api("org.springframework.boot:spring-boot-starter-security:3.3.1")
    api("org.springframework.boot:spring-boot-starter-data-jdbc:3.3.1")
    api("org.jetbrains.kotlin:kotlin-maven-allopen:2.0.0")
    api("org.jetbrains.kotlin:kotlin-stdlib:2.0.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.9.23")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.2")
}

group = "ru.emacs"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
