INSERT INTO users (email, createdat, e_status, is_email_verified, password, credential_expired)
VALUES ('SYSTEM', current_timestamp, 'ACTIVE', false, ' ', current_timestamp),
       ('email1@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email2@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email3@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email4@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email5@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email6@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email7@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email8@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email9@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email10@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email11@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email12@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email13@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email14@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email15@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email16@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email17@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email18@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email19@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months'),
       ('email20@one.ru', current_timestamp, 'ACTIVE', false,
        'IiyFPNZ/BThEuN/4IvQELH+dXL8KFToHS9eoGuhg70g=', current_timestamp + '3 months')